#!/bin/sh
 
if [ ! -d "~/.robotloader" ]; then
	mkdir -p ~/.robotloader
	cp -rf /etc/robotloader/* ~/.robotloader/
	chmod 600 ~/.robotloader/*
fi

cd /usr/share/robotloader

java -Xmx256m -Djava.ext.dirs="/usr/share/java" -Djava.library.path="/usr/lib/jni" -jar RobotLoader_lib.jar -logdir="/var/log/robotloader" -configdir="/home/${USER}/.robotloader"
