joint_limits:
  orientation:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  shoulder:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  ellbow:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  wrist_bend:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  wrist_rotate:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  gripper:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false