/usr/share/robotloader/examples/*.*
/usr/share/robotloader/examples/RobotArmLib/*/*.c
/usr/share/robotloader/examples/RobotArmLib/*/*.h
/usr/share/robotloader/examples/RobotArmLib/*/*.o
/usr/share/robotloader/examples/RobotArmLib/*.*
/usr/share/robotloader/examples/RobotArmExamples/*/*.c
/usr/share/robotloader/examples/RobotArmExamples/*/*.h
/usr/share/robotloader/examples/RobotArmExamples/*/*.pnp*
/usr/share/robotloader/examples/RobotArmExamples/*/Makefile
/usr/share/robotloader/examples/RobotArmExamples/Calibrate_*/*.hex
/usr/share/robotloader/examples/RobotArmExamples/Example_/*.hex
/usr/share/cmake-2.8/Modules/FindArexxRobotArm.cmake
/usr/share/cmake-2.8/Modules/arexx_robot_arm_crosscompile.cmake


